version: "3.8"

services:
  geth:
    image: docker.io/ethereum/client-go:latest
    restart: always
    environment:
      GETH_DEV: "true"
      GETH_HTTP: "true"
      GETH_HTTP_API: "personal,eth,net,web3,debug"
      GETH_RPC_ALLOW_UNPROTECTED_TXS: "true"
    ports:
      - 8545:8545

  setup:
    build:
      context: .
      dockerfile: docker/setup/Dockerfile
    restart: never
    environment:
      PLAYGROUND_GETH_URL: "http://geth:8545"
      PLAYGROUND_BUNDLER_URL: "http://bundler:8545"
    depends_on:
      - geth

  bundler:
    build:
      context: .
      dockerfile: docker/bundler/Dockerfile
    restart: always
    command: ["bundler", "--network", "http://geth:8545"]
    ports:
      - 3000:3000
    depends_on:
      setup:
        condition: service_completed_successfully
